from __future__ import annotations

import io
from contextlib import redirect_stdout
from pathlib import Path
import sys
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


import requests
import streamlit as st


ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))


from services.genai_service import fetch_economic_answer



st.title("MagistrAssistant : AI assistant for economic questions, helped by MistralAI")
st.write("This application allows you to ask economic questions and receive answers generated by a language model.\n The responses are based on the knowledge of the model, which has been trained on a wide range of economic data and literature.")